### ISSUE TITLE
Cannot log into Homer

### ISSUE THREAD

**Issue by tcreek** [sipcapture/homer5-docker#84]
For the Docker image, Homer 7 HEP Elastic, just cloned/tested today. 

When trying to  log into the portal on port 9090, there is no response, or indication of bad login.

I am using the usual credentials admin/test123.

**Comment by overload08** [comment]
Hi.

I have this issue too. I tried admin/test123, admin/test1234, admin/homerSeven but none ok...

For test123, I have some logs : 

`
    at postValidate (/app/node_modules/hapi/lib/validation.js:85:48),
    Error: child "password" fails because ["password" length must be at least 8 characters long],
Server started,
Debug: validation, error, payload ,
    at internals.Object._validateWithOptions (/app/node_modules/joi/lib/types/any/index.js:671:20),
    at module.exports.internals.Any.root.validate (/app/node_modules/joi/lib/index.js:139:23),
    at Object.internals.input (/app/node_modules/hapi/lib/validation.js:144:20),
    at exports.payload (/app/node_modules/hapi/lib/validation.js:44:22),
    at each (/app/node_modules/hapi/lib/request.js:401:16),
    at iterate (/app/node_modules/items/lib/index.js:36:13),
    at done (/app/node_modules/items/lib/index.js:28:25),
    at internals.Auth.payload (/app/node_modules/hapi/lib/auth.js:235:16),
    at onParsed (/app/node_modules/hapi/lib/route.js:341:20),
    at Subtext.parse (/app/node_modules/hapi/lib/route.js:380:20),
    at next (/app/node_modules/subtext/lib/index.js:45:26),
    at object (/app/node_modules/subtext/lib/index.js:172:20)`

**Comment by overload08** [comment]
Found it! The password is "sipcapture"

**Comment by tcreek** [comment]
Thanks for that. I guess it could be construed as an issue as it is not documented.

**Comment by lmangani** [comment]
As things get tested and stable, we'll release a full guide - Right now,
this is documented in the Docker containers README files, ie:


   - Homer localhost:9080 (admin/sipcapture)
